import React from 'react';
import { X, FileText, Download, Share2, CheckCircle2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useTranslation } from 'react-i18next';

interface ReportModalProps {
    isOpen: boolean;
    onClose: () => void;
    title: string;
    content: React.ReactNode;
    type?: 'success' | 'warning' | 'info';
}

const ReportModal: React.FC<ReportModalProps> = ({ isOpen, onClose, title, content, type = 'success' }) => {
    const { t } = useTranslation();

    if (!isOpen) return null;

    const typeConfig = {
        success: 'text-primary-600 bg-primary-100 dark:bg-primary-900/30 dark:text-primary-400 border-primary-200 dark:border-primary-800',
        warning: 'text-yellow-600 bg-yellow-100 dark:bg-yellow-900/30 dark:text-yellow-400 border-yellow-200 dark:border-yellow-800',
        info: 'text-blue-600 bg-blue-100 dark:bg-blue-900/30 dark:text-blue-400 border-blue-200 dark:border-blue-800',
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 sm:items-center items-end">
                {/* Backdrop */}
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    onClick={onClose}
                    className="fixed inset-0 bg-gray-900/60 backdrop-blur-sm"
                />

                {/* Modal Container */}
                <motion.div
                    initial={{ opacity: 0, y: 50, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 20, scale: 0.95 }}
                    className="relative w-full max-w-2xl bg-white dark:bg-gray-800 rounded-[2rem] shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
                >
                    {/* Header */}
                    <div className="px-6 py-5 border-b border-gray-100 dark:border-gray-700/50 flex items-center justify-between sticky top-0 bg-white/80 dark:bg-gray-800/80 backdrop-blur-md z-10">
                        <div className="flex items-center gap-3">
                            <div className={`p-2.5 rounded-xl border ${typeConfig[type]}`}>
                                <FileText size={20} />
                            </div>
                            <div>
                                <h3 className="text-xl font-black font-display text-gray-900 dark:text-white leading-none mb-1">Detailed Report</h3>
                                <p className="text-xs font-bold uppercase tracking-widest text-gray-400">{title}</p>
                            </div>
                        </div>
                        <button
                            onClick={onClose}
                            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-300 rounded-xl transition-all"
                        >
                            <X size={20} />
                        </button>
                    </div>

                    {/* Scrollable Content Area */}
                    <div className="p-6 md:p-8 overflow-y-auto custom-scrollbar flex-1 relative">
                        {/* Watermark */}
                        <div className="absolute top-8 right-8 opacity-5 pointer-events-none">
                            <FileText size={160} />
                        </div>

                        <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none prose-headings:font-display prose-headings:font-black prose-a:text-primary-500">
                            {content}
                        </div>
                    </div>

                    {/* Footer Actions */}
                    <div className="px-6 py-4 bg-gray-50 dark:bg-gray-900/50 border-t border-gray-100 dark:border-gray-700/50 flex items-center justify-between gap-4 mt-auto">
                        <div className="flex items-center gap-2 text-xs font-bold text-gray-400">
                            <CheckCircle2 size={14} className="text-primary-500" />
                            Generated by AgriFlux AI
                        </div>
                        <div className="flex items-center gap-2">
                            <button className="btn-outline py-2 px-4 shadow-sm text-xs font-bold hidden sm:flex">
                                <Share2 size={16} /> Share
                            </button>
                            <button className="btn-primary py-2 px-4 shadow-sm text-xs font-bold" onClick={onClose}>
                                <Download size={16} /> Download PDF
                            </button>
                        </div>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
};

export default ReportModal;
